# Generated by Django 5.0 on 2023-12-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cuisine',
            field=models.CharField(max_length=100),
        ),
    ]
