# Generated by Django 5.0 on 2023-12-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsmigrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='drink',
            new_name='drink_name',
        ),
    ]
